### ISSUE TITLE
Unable to install this package using pip

### ISSUE THREAD

**Issue by kubaracek** [andreyrusanov/nose-env-config#4]
```
Collecting nose-env-config (from -r requirements.txt (line 6))
  Downloading nose_env_config-0.1.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ypol2wxj/nose-env-config/setup.py", line 19, in <module>
        long_description=open('README.rst').read(),
    FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'
```

**Comment by andreyrusanov** [comment]
@JacobJakub  thanks for report! I will take a look during weekend.

**Comment by andreyrusanov** [comment]
@JacobJakub updated and published on PyPI. Now you should be able to install it without any problem. 
Please note it may be cached, so it would be better to run `pip install` with `--no-cache-dir` flag.
